import { BookOpen, FileText } from "./page-dependencies";

export const readingTestCards = [
  {
    id: "reading-forgotten-forest-test-55",
    title: "The Forgotten Forest — Test 55",
    meta: "Cambridge Official · Passage 1",
    source: "cambridge",
    format: "passage_1",
    access: "free",
    order: 55,
    badges: ["Free"],
    button: "Start Test",
    buttonVariant: "outline",
    icon: BookOpen,
    iconClassName: "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300",
    href: "/tests?type=reading",
  },
  {
    id: "reading-cambridge-20-test-1",
    title: "Cambridge 20 — Reading Test 1",
    meta: "Cambridge Official · Full Test",
    source: "cambridge",
    format: "full",
    access: "premium",
    order: 54,
    badges: ["Premium"],
    button: "Unlock",
    buttonVariant: "outline",
    icon: FileText,
    iconClassName: "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-300",
    href: "/subscription",
  },
  {
    id: "reading-cambridge-20-test-2",
    title: "Cambridge 20 — Reading Test 2",
    meta: "Cambridge Official · Full Test",
    source: "cambridge",
    format: "full",
    access: "premium",
    order: 53,
    badges: ["Premium"],
    button: "Unlock",
    buttonVariant: "outline",
    icon: FileText,
    iconClassName: "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-300",
    href: "/subscription",
  },
  {
    id: "reading-cambridge-20-test-3",
    title: "Cambridge 20 — Reading Test 3",
    meta: "Cambridge Official · Full Test",
    source: "cambridge",
    format: "full",
    access: "premium",
    order: 52,
    badges: ["Premium"],
    button: "Unlock",
    buttonVariant: "outline",
    icon: FileText,
    iconClassName: "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-300",
    href: "/subscription",
  },
  {
    id: "reading-cambridge-20-test-4",
    title: "Cambridge 20 — Reading Test 4",
    meta: "Cambridge Official · Full Test",
    source: "cambridge",
    format: "full",
    access: "premium",
    order: 51,
    badges: ["Premium"],
    button: "Unlock",
    buttonVariant: "outline",
    icon: FileText,
    iconClassName: "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-300",
    href: "/subscription",
  },
  {
    id: "reading-recent-exam-paper-7",
    title: "Recent Exam Paper 7",
    meta: "Recent Exam Papers · Full Test",
    source: "real_exam",
    format: "full",
    access: "premium",
    order: 50,
    badges: ["Premium"],
    button: "Unlock",
    buttonVariant: "outline",
    icon: FileText,
    iconClassName: "bg-violet-50 text-violet-500 dark:bg-violet-500/10 dark:text-violet-300",
    href: "/subscription",
  },
  {
    id: "reading-climate-change-solutions-test-41",
    title: "Climate Change Solutions — Test 41",
    meta: "Cambridge Official · Passage 3",
    source: "cambridge",
    format: "passage_3",
    access: "free",
    order: 41,
    badges: ["Free"],
    button: "Start Test",
    buttonVariant: "outline",
    icon: BookOpen,
    iconClassName: "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300",
    href: "/tests?type=reading",
  },
  {
    id: "reading-future-of-work-test-32",
    title: "The Future of Work — Test 32",
    meta: "Exam Practice Tests · Passage 2",
    source: "custom",
    format: "passage_2",
    access: "free",
    order: 32,
    badges: ["Free", "In progress"],
    button: "Continue",
    buttonVariant: "solid",
    icon: FileText,
    iconClassName: "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300",
    href: "/exam-preview/reading?mode=practice",
  },
  {
    id: "reading-survey-form-test-12",
    title: "Survey Form — Test 12",
    meta: "Exam Practice Tests · Passage 1",
    source: "custom",
    format: "passage_1",
    access: "free",
    order: 12,
    badges: ["Free"],
    button: "Start Test",
    buttonVariant: "outline",
    icon: FileText,
    iconClassName: "bg-violet-50 text-violet-500 dark:bg-violet-500/10 dark:text-violet-300",
    href: "/tests?type=reading",
  },
  {
    id: "reading-cambridge-19-test-2",
    title: "Cambridge 19 — Reading Test 2",
    meta: "Cambridge Official · Full Test",
    source: "cambridge",
    format: "full",
    access: "premium",
    order: 11,
    badges: ["Premium"],
    button: "Unlock",
    buttonVariant: "outline",
    icon: FileText,
    iconClassName: "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-300",
    href: "/subscription",
  },
  {
    id: "reading-impact-of-tourism-test-23",
    title: "The Impact of Tourism — Test 23",
    meta: "Exam Practice Tests · Passage 2",
    source: "custom",
    format: "passage_2",
    access: "free",
    order: 10,
    badges: ["Free", "Completed"],
    button: "Review",
    buttonVariant: "solid",
    icon: FileText,
    iconClassName: "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300",
    href: "/history",
  },
] as const;
