import asyncio
from uuid import UUID
from app.db.session import get_session_maker
from app.models.attempt import Attempt
import copy

async def update_attempt():
    session_maker = get_session_maker()
    async with session_maker() as session:
        attempt_id = UUID("20819e86-43a6-46d0-81b7-dd7327716f47")
        attempt = await session.get(Attempt, attempt_id)
        if attempt:
            meta = copy.deepcopy(attempt.attempt_metadata)
            for item in meta.get("scoring_items", []):
                item["explanation"] = "This is a mocked explanation generated by AI. It explains why the answer is correct."
                item["explanation_reference"] = {"quote": "This is a mock quote from the text."}
            attempt.attempt_metadata = meta
            session.add(attempt)
            await session.commit()
            print("Attempt updated!")
asyncio.run(update_attempt())
