"use client";
export { default as React } from "react";
export { useEffect } from "react";
export { X } from "lucide-react";
export { Trophy } from "lucide-react";
export { Target } from "lucide-react";
export { Flame } from "lucide-react";
export { BookOpen } from "lucide-react";
export { Clock } from "lucide-react";
export { Award } from "lucide-react";
export { Crown } from "lucide-react";
export { default as Image } from "next/image";
