"""Backward-compatible facade for admin authentication services."""

from app.services.admin_auth_accounts import (
    authenticate_admin,
    authenticate_admin_by_phone_number,
    build_admin_principal,
    create_admin_account,
    get_admin_by_id,
    get_admin_by_login,
    get_admin_by_phone_number,
    update_admin_security_settings,
)
from app.services.admin_auth_password_reset import (
    consume_admin_password_reset_token,
    get_admin_password_reset_challenge,
    parse_admin_password_reset_token,
)
from app.services.admin_auth_shared import (
    ADMIN_CREDENTIAL_FAILURE_WINDOW_SECONDS,
    ADMIN_CREDENTIAL_MAX_FAILURES,
    ADMIN_LOGIN_OTP_MAX_ATTEMPTS,
    ADMIN_LOGIN_OTP_PURPOSE,
    ADMIN_LOGIN_OTP_TTL_SECONDS,
    ADMIN_OTP_ISSUE_MAX_PER_MINUTE,
    ADMIN_PASSWORD_MIN_LENGTH,
    ADMIN_PASSWORD_RESET_IP_DAILY_MAX,
    ADMIN_PASSWORD_RESET_IP_DAILY_WINDOW_SECONDS,
    ADMIN_PASSWORD_RESET_IP_SHORT_MAX,
    ADMIN_PASSWORD_RESET_IP_SHORT_WINDOW_SECONDS,
    ADMIN_PASSWORD_RESET_MAX_ATTEMPTS,
    ADMIN_PASSWORD_RESET_PHONE_DAILY_MAX,
    ADMIN_PASSWORD_RESET_PHONE_DAILY_WINDOW_SECONDS,
    ADMIN_PASSWORD_RESET_PHONE_SHORT_MAX,
    ADMIN_PASSWORD_RESET_PHONE_SHORT_WINDOW_SECONDS,
    ADMIN_PASSWORD_RESET_PURPOSE,
    ADMIN_PASSWORD_RESET_TTL_SECONDS,
    AdminOtpFailure,
    build_admin_otp_message,
    build_admin_password_reset_message,
    build_admin_password_reset_reply_markup,
    build_admin_password_reset_success_message,
    build_admin_password_reset_url,
    consume_admin_login_otp,
    generate_admin_otp_code,
    is_local_admin_reset_url,
    normalize_login,
    normalize_phone_number,
)
from app.services.admin_auth_throttle import AdminAuthThrottle, get_admin_auth_throttle

_normalize_login = normalize_login
_is_local_admin_reset_url = is_local_admin_reset_url

__all__ = [
    "ADMIN_CREDENTIAL_FAILURE_WINDOW_SECONDS",
    "ADMIN_CREDENTIAL_MAX_FAILURES",
    "ADMIN_LOGIN_OTP_MAX_ATTEMPTS",
    "ADMIN_LOGIN_OTP_PURPOSE",
    "ADMIN_LOGIN_OTP_TTL_SECONDS",
    "ADMIN_OTP_ISSUE_MAX_PER_MINUTE",
    "ADMIN_PASSWORD_MIN_LENGTH",
    "ADMIN_PASSWORD_RESET_IP_DAILY_MAX",
    "ADMIN_PASSWORD_RESET_IP_DAILY_WINDOW_SECONDS",
    "ADMIN_PASSWORD_RESET_IP_SHORT_MAX",
    "ADMIN_PASSWORD_RESET_IP_SHORT_WINDOW_SECONDS",
    "ADMIN_PASSWORD_RESET_MAX_ATTEMPTS",
    "ADMIN_PASSWORD_RESET_PHONE_DAILY_MAX",
    "ADMIN_PASSWORD_RESET_PHONE_DAILY_WINDOW_SECONDS",
    "ADMIN_PASSWORD_RESET_PHONE_SHORT_MAX",
    "ADMIN_PASSWORD_RESET_PHONE_SHORT_WINDOW_SECONDS",
    "ADMIN_PASSWORD_RESET_PURPOSE",
    "ADMIN_PASSWORD_RESET_TTL_SECONDS",
    "AdminAuthThrottle",
    "AdminOtpFailure",
    "authenticate_admin",
    "authenticate_admin_by_phone_number",
    "build_admin_otp_message",
    "build_admin_password_reset_message",
    "build_admin_password_reset_reply_markup",
    "build_admin_password_reset_success_message",
    "build_admin_password_reset_url",
    "build_admin_principal",
    "consume_admin_login_otp",
    "consume_admin_password_reset_token",
    "create_admin_account",
    "generate_admin_otp_code",
    "get_admin_auth_throttle",
    "get_admin_by_id",
    "get_admin_by_login",
    "get_admin_by_phone_number",
    "get_admin_password_reset_challenge",
    "normalize_phone_number",
    "parse_admin_password_reset_token",
    "update_admin_security_settings",
]
