"""Add missing tables

Revision ID: 9cf84eb1036b
Revises: 20260415_000002
Create Date: 2026-04-15 10:08:24.592118
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '9cf84eb1036b'
down_revision = '20260415_000002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payment_paused', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_table('promo_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_codes'))
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_table('telegram_login_codes',
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_login_codes'))
    )
    op.create_index(op.f('ix_telegram_login_codes_telegram_id'), 'telegram_login_codes', ['telegram_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_audit_log_admin_id_admins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('audit_logs',
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=120), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_audit_logs_admin_id_admins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_table('gift_codes',
    sa.Column('purchaser_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PAUSED', 'PENDING', 'COMPLETED', 'FAILED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_gift_codes_plan_id_plans')),
    sa.ForeignKeyConstraint(['purchaser_user_id'], ['users.id'], name=op.f('fk_gift_codes_purchaser_user_id_users')),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_gift_codes_recipient_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gift_codes'))
    )
    op.create_index(op.f('ix_gift_codes_code'), 'gift_codes', ['code'], unique=True)
    op.create_index(op.f('ix_gift_codes_purchaser_user_id'), 'gift_codes', ['purchaser_user_id'], unique=False)
    op.create_index(op.f('ix_gift_codes_recipient_user_id'), 'gift_codes', ['recipient_user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_success_enabled', sa.Boolean(), nullable=False),
    sa.Column('premium_expiring_enabled', sa.Boolean(), nullable=False),
    sa.Column('premium_expired_enabled', sa.Boolean(), nullable=False),
    sa.Column('gift_received_enabled', sa.Boolean(), nullable=False),
    sa.Column('new_test_enabled', sa.Boolean(), nullable=False),
    sa.Column('weekly_summary_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences'))
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('payment_success', 'premium_expiring', 'premium_expired', 'new_test', 'gift_received', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_telegram', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('payments',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PAUSED', 'PENDING', 'COMPLETED', 'FAILED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_payments_plan_id_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_sessions_refresh_token_hash'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('SUPER_ADMIN', 'ADMIN', name='adminrole', native_enum=False),
               existing_nullable=False)
    op.alter_column('attempts', 'test_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('READING', 'LISTENING', name='testtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('attempts', 'mode',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PRACTICE', 'EXAM', name='attemptmode', native_enum=False),
               existing_nullable=False)
    op.alter_column('attempts', 'scope',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('FULL', 'SECTION', name='attemptscope', native_enum=False),
               existing_nullable=False)
    op.alter_column('attempts', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', 'AUTO_SUBMITTED', name='attemptstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('question_groups', 'question_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('READING_MC_SINGLE', 'READING_MC_MULTIPLE', 'READING_TRUE_FALSE_NOT_GIVEN', 'READING_YES_NO_NOT_GIVEN', 'READING_MATCHING_INFORMATION', 'READING_MATCHING_HEADINGS', 'READING_MATCHING_FEATURES', 'READING_MATCHING_SENTENCE_ENDINGS', 'READING_SENTENCE_COMPLETION', 'READING_SUMMARY_COMPLETION_WORDBANK', 'READING_SUMMARY_COMPLETION_FREETEXT', 'READING_NOTE_COMPLETION', 'READING_TABLE_COMPLETION', 'READING_FLOWCHART_COMPLETION', 'READING_DIAGRAM_LABELING', 'READING_SHORT_ANSWER', 'LISTENING_MC_SINGLE', 'LISTENING_MC_MULTIPLE', 'LISTENING_MATCHING', 'LISTENING_PLAN_MAP_LABELING', 'LISTENING_FORM_COMPLETION', 'LISTENING_NOTE_COMPLETION', 'LISTENING_TABLE_COMPLETION', 'LISTENING_FLOWCHART_COMPLETION', 'LISTENING_SUMMARY_COMPLETION', 'LISTENING_SENTENCE_COMPLETION', 'LISTENING_SHORT_ANSWER', name='questiontype', native_enum=False),
               existing_nullable=False)
    op.alter_column('tests', 'type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('READING', 'LISTENING', name='testtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('tests', 'access_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PUBLIC', 'PREMIUM', name='accesstype', native_enum=False),
               existing_nullable=False)
    op.alter_column('tests', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='teststatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('tests', 'source',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('CAMBRIDGE', 'REAL_EXAM', 'CUSTOM', name='testsource', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_tests_status'), table_name='tests')
    op.create_foreign_key(op.f('fk_tests_created_by_admins'), 'tests', 'admins', ['created_by'], ['id'])
    op.drop_constraint(op.f('uq_users_phone'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_telegram_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_unique_constraint(op.f('uq_users_telegram_id'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_phone'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_tests_created_by_admins'), 'tests', type_='foreignkey')
    op.create_index(op.f('ix_tests_status'), 'tests', ['status'], unique=False)
    op.alter_column('tests', 'source',
               existing_type=sa.Enum('CAMBRIDGE', 'REAL_EXAM', 'CUSTOM', name='testsource', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('tests', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='teststatus', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('tests', 'access_type',
               existing_type=sa.Enum('PUBLIC', 'PREMIUM', name='accesstype', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('tests', 'type',
               existing_type=sa.Enum('READING', 'LISTENING', name='testtype', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('question_groups', 'question_type',
               existing_type=sa.Enum('READING_MC_SINGLE', 'READING_MC_MULTIPLE', 'READING_TRUE_FALSE_NOT_GIVEN', 'READING_YES_NO_NOT_GIVEN', 'READING_MATCHING_INFORMATION', 'READING_MATCHING_HEADINGS', 'READING_MATCHING_FEATURES', 'READING_MATCHING_SENTENCE_ENDINGS', 'READING_SENTENCE_COMPLETION', 'READING_SUMMARY_COMPLETION_WORDBANK', 'READING_SUMMARY_COMPLETION_FREETEXT', 'READING_NOTE_COMPLETION', 'READING_TABLE_COMPLETION', 'READING_FLOWCHART_COMPLETION', 'READING_DIAGRAM_LABELING', 'READING_SHORT_ANSWER', 'LISTENING_MC_SINGLE', 'LISTENING_MC_MULTIPLE', 'LISTENING_MATCHING', 'LISTENING_PLAN_MAP_LABELING', 'LISTENING_FORM_COMPLETION', 'LISTENING_NOTE_COMPLETION', 'LISTENING_TABLE_COMPLETION', 'LISTENING_FLOWCHART_COMPLETION', 'LISTENING_SUMMARY_COMPLETION', 'LISTENING_SENTENCE_COMPLETION', 'LISTENING_SHORT_ANSWER', name='questiontype', native_enum=False),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('attempts', 'status',
               existing_type=sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', 'AUTO_SUBMITTED', name='attemptstatus', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('attempts', 'scope',
               existing_type=sa.Enum('FULL', 'SECTION', name='attemptscope', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('attempts', 'mode',
               existing_type=sa.Enum('PRACTICE', 'EXAM', name='attemptmode', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('attempts', 'test_type',
               existing_type=sa.Enum('READING', 'LISTENING', name='testtype', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('admins', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', name='adminrole', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_gift_codes_recipient_user_id'), table_name='gift_codes')
    op.drop_index(op.f('ix_gift_codes_purchaser_user_id'), table_name='gift_codes')
    op.drop_index(op.f('ix_gift_codes_code'), table_name='gift_codes')
    op.drop_table('gift_codes')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_telegram_login_codes_telegram_id'), table_name='telegram_login_codes')
    op.drop_table('telegram_login_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_table('plans')
    # ### end Alembic commands ###

