import {
  Activity,
  AlarmClock,
  Anchor,
  Apple,
  Archive,
  Award,
  Backpack,
  Baby,
  Banknote,
  BarChart3,
  Bath,
  Battery,
  Beaker,
  Bell,
  Bike,
  Bird,
  Book,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Building2,
  Bus,
  Calculator,
  Calendar,
  Camera,
  Candy,
  Car,
  Cat,
  ChefHat,
  Cherry,
  ClipboardList,
  Clock3,
  Cloud,
  CloudRain,
  CloudSun,
  Code,
  Coffee,
  Coins,
  Compass,
  Contact,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  Dog,
  DollarSign,
  Droplets,
  Drum,
  Dumbbell,
  Egg,
  Eye,
  Factory,
  Feather,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Grape,
  Guitar,
  Hammer,
  Hand,
  HandHeart,
  Handshake,
  HardHat,
  Headphones,
  Headset,
  Heart,
  Home,
  Hospital,
  Hotel,
  Hourglass,
  IceCream,
  Image,
  Inbox,
  Joystick,
  Key,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  List,
  Lock,
  Luggage,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic2,
  Microscope,
  Milk,
  Monitor,
  Moon,
  Mountain,
  Music,
  Music2,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  Package,
  Paintbrush,
  Palette,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  Pen,
  Pencil,
  PenLine,
  Phone,
  Piano,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Play,
  Plug,
  Podcast,
  Popcorn,
  Presentation,
  Printer,
  Puzzle,
  Radio,
  Rainbow,
  Receipt,
  Recycle,
  Rocket,
  Route,
  Ruler,
  Sailboat,
  Scale,
  School,
  Scissors,
  Scroll,
  Send,
  Server,
  Settings,
  Share2,
  Shell,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Signpost,
  Skull,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  Sprout,
  Stamp,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Sword,
  Syringe,
  Tablet,
  Tag,
  Target,
  Telescope,
  Tent,
  TestTube,
  Thermometer,
  ThumbsUp,
  Ticket,
  Timer,
  TrainFront,
  TreePine,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Umbrella,
  User,
  UserCheck,
  UserPlus,
  Users,
  UtensilsCrossed,
  Vegan,
  Video,
  Volume2,
  Wallet,
  Watch,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const SPEAKING_ICON_TONES = ["purple", "blue", "green", "orange", "pink"] as const;

export type SpeakingIconTone = (typeof SPEAKING_ICON_TONES)[number];

export type SpeakingIconOption = {
  id: string;
  label: string;
  Icon: LucideIcon;
};

export const SPEAKING_TOPIC_ICONS: SpeakingIconOption[] = [
  { id: "home", label: "Home", Icon: Home },
  { id: "briefcase", label: "Work", Icon: Briefcase },
  { id: "users", label: "People", Icon: Users },
  { id: "baby", label: "Family", Icon: Baby },
  { id: "heart", label: "Health", Icon: Heart },
  { id: "hand-heart", label: "Care", Icon: HandHeart },
  { id: "smile", label: "Mood", Icon: Smile },
  { id: "clock", label: "Routine", Icon: Clock3 },
  { id: "alarm-clock", label: "Schedule", Icon: AlarmClock },
  { id: "calendar", label: "Calendar", Icon: Calendar },
  { id: "sun", label: "Weather", Icon: Sun },
  { id: "cloud", label: "Cloud", Icon: Cloud },
  { id: "moon", label: "Night", Icon: Moon },
  { id: "utensils", label: "Food", Icon: UtensilsCrossed },
  { id: "coffee", label: "Coffee", Icon: Coffee },
  { id: "apple", label: "Fruit", Icon: Apple },
  { id: "cherry", label: "Snacks", Icon: Cherry },
  { id: "plane", label: "Travel", Icon: Plane },
  { id: "car", label: "Car", Icon: Car },
  { id: "bus", label: "Transport", Icon: Bus },
  { id: "ship", label: "Sea", Icon: Ship },
  { id: "map-pin", label: "Place", Icon: MapPin },
  { id: "compass", label: "Direction", Icon: Compass },
  { id: "globe", label: "World", Icon: Globe },
  { id: "mountain", label: "Nature", Icon: Mountain },
  { id: "tent", label: "Camping", Icon: Tent },
  { id: "tree-pine", label: "Forest", Icon: TreePine },
  { id: "waves", label: "Water", Icon: Waves },
  { id: "flower", label: "Garden", Icon: Flower2 },
  { id: "leaf", label: "Environment", Icon: Leaf },
  { id: "monitor", label: "Tech", Icon: Monitor },
  { id: "laptop", label: "Laptop", Icon: Laptop },
  { id: "smartphone", label: "Phone", Icon: Smartphone },
  { id: "phone", label: "Call", Icon: Phone },
  { id: "wifi", label: "Internet", Icon: Wifi },
  { id: "headphones", label: "Audio", Icon: Headphones },
  { id: "gamepad", label: "Games", Icon: Gamepad2 },
  { id: "tv", label: "TV", Icon: Tv },
  { id: "film", label: "Movies", Icon: Film },
  { id: "camera", label: "Photo", Icon: Camera },
  { id: "music", label: "Music", Icon: Music },
  { id: "newspaper", label: "News", Icon: Newspaper },
  { id: "mail", label: "Email", Icon: Mail },
  { id: "megaphone", label: "Media", Icon: Megaphone },
  { id: "shopping-bag", label: "Shopping", Icon: ShoppingBag },
  { id: "wallet", label: "Money", Icon: Wallet },
  { id: "gift", label: "Gift", Icon: Gift },
  { id: "key", label: "Access", Icon: Key },
  { id: "shield", label: "Safety", Icon: Shield },
  { id: "book-open", label: "Reading", Icon: BookOpen },
  { id: "school", label: "School", Icon: School },
  { id: "graduation-cap", label: "Study", Icon: GraduationCap },
  { id: "languages", label: "Language", Icon: Languages },
  { id: "pen-line", label: "Writing", Icon: PenLine },
  { id: "lightbulb", label: "Ideas", Icon: Lightbulb },
  { id: "brain", label: "Thinking", Icon: Brain },
  { id: "target", label: "Goals", Icon: Target },
  { id: "star", label: "Skill", Icon: Star },
  { id: "trophy", label: "Success", Icon: Trophy },
  { id: "dumbbell", label: "Fitness", Icon: Dumbbell },
  { id: "bike", label: "Sport", Icon: Bike },
  { id: "stethoscope", label: "Medical", Icon: Stethoscope },
  { id: "pill", label: "Medicine", Icon: Pill },
  { id: "building", label: "City", Icon: Building2 },
  { id: "landmark", label: "Culture", Icon: Landmark },
  { id: "hotel", label: "Hotel", Icon: Hotel },
  { id: "flag", label: "Country", Icon: Flag },
  { id: "sparkles", label: "Festival", Icon: Sparkles },
  { id: "palette", label: "Art", Icon: Palette },
  { id: "message-circle", label: "Talk", Icon: MessageCircle },
  { id: "mic", label: "Speaking", Icon: Mic2 },
  { id: "rocket", label: "Future", Icon: Rocket },
  { id: "zap", label: "Energy", Icon: Zap },
  { id: "flame", label: "Trend", Icon: Flame },
  { id: "activity", label: "Activity", Icon: Activity },
  { id: "anchor", label: "Anchor", Icon: Anchor },
  { id: "archive", label: "Archive", Icon: Archive },
  { id: "award", label: "Award", Icon: Award },
  { id: "backpack", label: "Backpack", Icon: Backpack },
  { id: "banknote", label: "Cash", Icon: Banknote },
  { id: "bar-chart", label: "Stats", Icon: BarChart3 },
  { id: "bath", label: "Bath", Icon: Bath },
  { id: "battery", label: "Battery", Icon: Battery },
  { id: "beaker", label: "Science", Icon: Beaker },
  { id: "bell", label: "Alert", Icon: Bell },
  { id: "bird", label: "Bird", Icon: Bird },
  { id: "book", label: "Book", Icon: Book },
  { id: "bookmark", label: "Bookmark", Icon: Bookmark },
  { id: "bot", label: "AI", Icon: Bot },
  { id: "box", label: "Package", Icon: Box },
  { id: "brush", label: "Design", Icon: Brush },
  { id: "calculator", label: "Math", Icon: Calculator },
  { id: "candy", label: "Candy", Icon: Candy },
  { id: "cat", label: "Pet", Icon: Cat },
  { id: "chef-hat", label: "Cooking", Icon: ChefHat },
  { id: "clipboard", label: "Notes", Icon: ClipboardList },
  { id: "cloud-rain", label: "Rain", Icon: CloudRain },
  { id: "cloud-sun", label: "Sunny", Icon: CloudSun },
  { id: "code", label: "Code", Icon: Code },
  { id: "coins", label: "Coins", Icon: Coins },
  { id: "contact", label: "Contact", Icon: Contact },
  { id: "cookie", label: "Cookie", Icon: Cookie },
  { id: "cpu", label: "Computer", Icon: Cpu },
  { id: "credit-card", label: "Card", Icon: CreditCard },
  { id: "croissant", label: "Bakery", Icon: Croissant },
  { id: "crown", label: "Premium", Icon: Crown },
  { id: "dog", label: "Dog", Icon: Dog },
  { id: "dollar", label: "Dollar", Icon: DollarSign },
  { id: "droplet", label: "Drink", Icon: Droplets },
  { id: "drum", label: "Music drum", Icon: Drum },
  { id: "egg", label: "Breakfast", Icon: Egg },
  { id: "eye", label: "View", Icon: Eye },
  { id: "factory", label: "Industry", Icon: Factory },
  { id: "feather", label: "Feather", Icon: Feather },
  { id: "file-text", label: "Document", Icon: FileText },
  { id: "fish", label: "Fish", Icon: Fish },
  { id: "footprints", label: "Walk", Icon: Footprints },
  { id: "gem", label: "Gem", Icon: Gem },
  { id: "glasses", label: "Glasses", Icon: Glasses },
  { id: "grape", label: "Grape", Icon: Grape },
  { id: "guitar", label: "Guitar", Icon: Guitar },
  { id: "hammer", label: "Build", Icon: Hammer },
  { id: "hand", label: "Hand", Icon: Hand },
  { id: "handshake", label: "Deal", Icon: Handshake },
  { id: "hard-hat", label: "Construction", Icon: HardHat },
  { id: "headset", label: "Headset", Icon: Headset },
  { id: "hospital", label: "Hospital", Icon: Hospital },
  { id: "hourglass", label: "Time", Icon: Hourglass },
  { id: "ice-cream", label: "Ice cream", Icon: IceCream },
  { id: "image", label: "Image", Icon: Image },
  { id: "inbox", label: "Inbox", Icon: Inbox },
  { id: "joystick", label: "Joystick", Icon: Joystick },
  { id: "lamp", label: "Lamp", Icon: Lamp },
  { id: "layers", label: "Layers", Icon: Layers },
  { id: "library", label: "Library", Icon: Library },
  { id: "life-buoy", label: "Support", Icon: LifeBuoy },
  { id: "link", label: "Link", Icon: Link },
  { id: "list", label: "List", Icon: List },
  { id: "lock", label: "Lock", Icon: Lock },
  { id: "luggage", label: "Luggage", Icon: Luggage },
  { id: "magnet", label: "Magnet", Icon: Magnet },
  { id: "map", label: "Map", Icon: MapIcon },
  { id: "medal", label: "Medal", Icon: Medal },
  { id: "message-square", label: "Chat", Icon: MessageSquare },
  { id: "microscope", label: "Lab", Icon: Microscope },
  { id: "milk", label: "Milk", Icon: Milk },
  { id: "music2", label: "Tunes", Icon: Music2 },
  { id: "navigation", label: "Navigate", Icon: Navigation },
  { id: "network", label: "Network", Icon: Network },
  { id: "notebook", label: "Notebook", Icon: Notebook },
  { id: "paintbrush", label: "Paint", Icon: Paintbrush },
  { id: "parking", label: "Parking", Icon: ParkingCircle },
  { id: "party", label: "Party", Icon: PartyPopper },
  { id: "paw", label: "Animal", Icon: PawPrint },
  { id: "pen", label: "Pen", Icon: Pen },
  { id: "pencil", label: "Pencil", Icon: Pencil },
  { id: "piano", label: "Piano", Icon: Piano },
  { id: "pie-chart", label: "Chart", Icon: PieChart },
  { id: "piggy-bank", label: "Savings", Icon: PiggyBank },
  { id: "pizza", label: "Pizza", Icon: Pizza },
  { id: "play", label: "Play", Icon: Play },
  { id: "plug", label: "Plug", Icon: Plug },
  { id: "podcast", label: "Podcast", Icon: Podcast },
  { id: "popcorn", label: "Popcorn", Icon: Popcorn },
  { id: "presentation", label: "Slides", Icon: Presentation },
  { id: "printer", label: "Print", Icon: Printer },
  { id: "puzzle", label: "Puzzle", Icon: Puzzle },
  { id: "radio", label: "Radio", Icon: Radio },
  { id: "rainbow", label: "Rainbow", Icon: Rainbow },
  { id: "receipt", label: "Receipt", Icon: Receipt },
  { id: "recycle", label: "Recycle", Icon: Recycle },
  { id: "route", label: "Route", Icon: Route },
  { id: "ruler", label: "Measure", Icon: Ruler },
  { id: "sailboat", label: "Sail", Icon: Sailboat },
  { id: "scale", label: "Balance", Icon: Scale },
  { id: "scissors", label: "Cut", Icon: Scissors },
  { id: "scroll", label: "Scroll", Icon: Scroll },
  { id: "send", label: "Send", Icon: Send },
  { id: "server", label: "Server", Icon: Server },
  { id: "settings", label: "Settings", Icon: Settings },
  { id: "share", label: "Share", Icon: Share2 },
  { id: "shell", label: "Shell", Icon: Shell },
  { id: "shirt", label: "Fashion", Icon: Shirt },
  { id: "shopping-cart", label: "Cart", Icon: ShoppingCart },
  { id: "shovel", label: "Garden tool", Icon: Shovel },
  { id: "shower", label: "Shower", Icon: ShowerHead },
  { id: "signpost", label: "Signpost", Icon: Signpost },
  { id: "skull", label: "Skull", Icon: Skull },
  { id: "snowflake", label: "Snow", Icon: Snowflake },
  { id: "sofa", label: "Sofa", Icon: Sofa },
  { id: "soup", label: "Soup", Icon: Soup },
  { id: "speaker", label: "Speaker", Icon: Speaker },
  { id: "sprout", label: "Plant", Icon: Sprout },
  { id: "stamp", label: "Stamp", Icon: Stamp },
  { id: "store", label: "Store", Icon: Store },
  { id: "sunrise", label: "Sunrise", Icon: Sunrise },
  { id: "sunset", label: "Sunset", Icon: Sunset },
  { id: "sword", label: "Sword", Icon: Sword },
  { id: "syringe", label: "Injection", Icon: Syringe },
  { id: "tablet", label: "Tablet", Icon: Tablet },
  { id: "tag", label: "Tag", Icon: Tag },
  { id: "telescope", label: "Space", Icon: Telescope },
  { id: "test-tube", label: "Test", Icon: TestTube },
  { id: "thermometer", label: "Temp", Icon: Thermometer },
  { id: "thumbs-up", label: "Like", Icon: ThumbsUp },
  { id: "ticket", label: "Ticket", Icon: Ticket },
  { id: "timer", label: "Timer", Icon: Timer },
  { id: "train", label: "Train", Icon: TrainFront },
  { id: "trending-up", label: "Growth", Icon: TrendingUp },
  { id: "triangle", label: "Alert shape", Icon: Triangle },
  { id: "truck", label: "Delivery", Icon: Truck },
  { id: "turtle", label: "Turtle", Icon: Turtle },
  { id: "umbrella", label: "Umbrella", Icon: Umbrella },
  { id: "user", label: "User", Icon: User },
  { id: "user-check", label: "Verified", Icon: UserCheck },
  { id: "user-plus", label: "Add user", Icon: UserPlus },
  { id: "vegan", label: "Vegan", Icon: Vegan },
  { id: "video", label: "Video", Icon: Video },
  { id: "volume", label: "Volume", Icon: Volume2 },
  { id: "watch", label: "Watch", Icon: Watch },
  { id: "wheat", label: "Farm", Icon: Wheat },
  { id: "wind", label: "Wind", Icon: Wind },
  { id: "wine", label: "Wine", Icon: Wine },
  { id: "wrench", label: "Repair", Icon: Wrench },
];

const iconMap = new Map(SPEAKING_TOPIC_ICONS.map((item) => [item.id, item]));

export function resolveSpeakingIcon(iconId: string | null | undefined): SpeakingIconOption | null {
  if (!iconId) return null;
  return iconMap.get(iconId) ?? null;
}

export function isSpeakingIconTone(value: string | null | undefined): value is SpeakingIconTone {
  return Boolean(value && SPEAKING_ICON_TONES.includes(value as SpeakingIconTone));
}

export function iconsForPart(_part: 1 | 2 | 3): SpeakingIconOption[] {
  return SPEAKING_TOPIC_ICONS;
}

export function filterSpeakingIcons(icons: SpeakingIconOption[], query: string): SpeakingIconOption[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) {
    return icons;
  }

  return icons.filter((item) => {
    const haystack = `${item.label} ${item.id.replace(/-/g, " ")}`.toLowerCase();
    return haystack.includes(normalized);
  });
}

export const SPEAKING_ICON_TONE_STYLES: Record<SpeakingIconTone, string> = {
  purple: "bg-violet-100 text-violet-700 border-violet-200",
  blue: "bg-sky-100 text-sky-700 border-sky-200",
  green: "bg-emerald-100 text-emerald-700 border-emerald-200",
  orange: "bg-orange-100 text-orange-700 border-orange-200",
  pink: "bg-pink-100 text-pink-700 border-pink-200",
};
