import { Magnet, Map as MapIcon, Medal, MessageSquare, Microscope, Milk, Music2, Navigation, Network, Notebook, Paintbrush, ParkingCircle, PartyPopper, PawPrint, Pen, Pencil, Piano, PieChart, PiggyBank, Pizza, Play, Plug, Podcast, Popcorn, Presentation, Printer, Puzzle, Radio, Rainbow, Receipt, Recycle, Route, Ruler, Sailboat, Scale, Scissors, Scroll, Send, Server, Settings, Share2, Shell, Shirt, ShoppingCart, Shovel, ShowerHead, Signpost, Skull, Snowflake, Sofa, Soup, Speaker, Sprout, Stamp, Store, Sunrise, Sunset, Sword, Syringe, Tablet, Tag, Telescope, TestTube, Thermometer, ThumbsUp, Ticket, Timer, TrainFront, TrendingUp, Triangle } from "lucide-react";
import type { SpeakingIconOption } from "./speaking-icons-types";

export const SPEAKING_TOPIC_ICONS_PART_03: SpeakingIconOption[] = [
  { id: "magnet", label: "Magnet", Icon: Magnet },
  { id: "map", label: "Map", Icon: MapIcon },
  { id: "medal", label: "Medal", Icon: Medal },
  { id: "message-square", label: "Chat", Icon: MessageSquare },
  { id: "microscope", label: "Lab", Icon: Microscope },
  { id: "milk", label: "Milk", Icon: Milk },
  { id: "music2", label: "Tunes", Icon: Music2 },
  { id: "navigation", label: "Navigate", Icon: Navigation },
  { id: "network", label: "Network", Icon: Network },
  { id: "notebook", label: "Notebook", Icon: Notebook },
  { id: "paintbrush", label: "Paint", Icon: Paintbrush },
  { id: "parking", label: "Parking", Icon: ParkingCircle },
  { id: "party", label: "Party", Icon: PartyPopper },
  { id: "paw", label: "Animal", Icon: PawPrint },
  { id: "pen", label: "Pen", Icon: Pen },
  { id: "pencil", label: "Pencil", Icon: Pencil },
  { id: "piano", label: "Piano", Icon: Piano },
  { id: "pie-chart", label: "Chart", Icon: PieChart },
  { id: "piggy-bank", label: "Savings", Icon: PiggyBank },
  { id: "pizza", label: "Pizza", Icon: Pizza },
  { id: "play", label: "Play", Icon: Play },
  { id: "plug", label: "Plug", Icon: Plug },
  { id: "podcast", label: "Podcast", Icon: Podcast },
  { id: "popcorn", label: "Popcorn", Icon: Popcorn },
  { id: "presentation", label: "Slides", Icon: Presentation },
  { id: "printer", label: "Print", Icon: Printer },
  { id: "puzzle", label: "Puzzle", Icon: Puzzle },
  { id: "radio", label: "Radio", Icon: Radio },
  { id: "rainbow", label: "Rainbow", Icon: Rainbow },
  { id: "receipt", label: "Receipt", Icon: Receipt },
  { id: "recycle", label: "Recycle", Icon: Recycle },
  { id: "route", label: "Route", Icon: Route },
  { id: "ruler", label: "Measure", Icon: Ruler },
  { id: "sailboat", label: "Sail", Icon: Sailboat },
  { id: "scale", label: "Balance", Icon: Scale },
  { id: "scissors", label: "Cut", Icon: Scissors },
  { id: "scroll", label: "Scroll", Icon: Scroll },
  { id: "send", label: "Send", Icon: Send },
  { id: "server", label: "Server", Icon: Server },
  { id: "settings", label: "Settings", Icon: Settings },
  { id: "share", label: "Share", Icon: Share2 },
  { id: "shell", label: "Shell", Icon: Shell },
  { id: "shirt", label: "Fashion", Icon: Shirt },
  { id: "shopping-cart", label: "Cart", Icon: ShoppingCart },
  { id: "shovel", label: "Garden tool", Icon: Shovel },
  { id: "shower", label: "Shower", Icon: ShowerHead },
  { id: "signpost", label: "Signpost", Icon: Signpost },
  { id: "skull", label: "Skull", Icon: Skull },
  { id: "snowflake", label: "Snow", Icon: Snowflake },
  { id: "sofa", label: "Sofa", Icon: Sofa },
  { id: "soup", label: "Soup", Icon: Soup },
  { id: "speaker", label: "Speaker", Icon: Speaker },
  { id: "sprout", label: "Plant", Icon: Sprout },
  { id: "stamp", label: "Stamp", Icon: Stamp },
  { id: "store", label: "Store", Icon: Store },
  { id: "sunrise", label: "Sunrise", Icon: Sunrise },
  { id: "sunset", label: "Sunset", Icon: Sunset },
  { id: "sword", label: "Sword", Icon: Sword },
  { id: "syringe", label: "Injection", Icon: Syringe },
  { id: "tablet", label: "Tablet", Icon: Tablet },
  { id: "tag", label: "Tag", Icon: Tag },
  { id: "telescope", label: "Space", Icon: Telescope },
  { id: "test-tube", label: "Test", Icon: TestTube },
  { id: "thermometer", label: "Temp", Icon: Thermometer },
  { id: "thumbs-up", label: "Like", Icon: ThumbsUp },
  { id: "ticket", label: "Ticket", Icon: Ticket },
  { id: "timer", label: "Timer", Icon: Timer },
  { id: "train", label: "Train", Icon: TrainFront },
  { id: "trending-up", label: "Growth", Icon: TrendingUp },
  { id: "triangle", label: "Alert shape", Icon: Triangle },
];
