import { Activity, Anchor, Archive, Award, Backpack, Banknote, BarChart3, Bath, Battery, Beaker, Bell, Bird, Book, Bookmark, Bot, Box, Brush, Calculator, Candy, Cat, ChefHat, ClipboardList, CloudRain, CloudSun, Code, Coins, Contact, Cookie, Cpu, CreditCard, Croissant, Crown, Dog, DollarSign, Droplets, Drum, Egg, Eye, Factory, Feather, FileText, Fish, Flame, Footprints, Gem, Glasses, Grape, Guitar, Hammer, Hand, Handshake, HardHat, Headset, Hospital, Hourglass, IceCream, Image, Inbox, Joystick, Lamp, Layers, Library, LifeBuoy, Link, List, Lock, Luggage, Mic2, Rocket, Zap } from "lucide-react";
import type { SpeakingIconOption } from "./speaking-icons-types";

export const SPEAKING_TOPIC_ICONS_PART_02: SpeakingIconOption[] = [
  { id: "mic", label: "Speaking", Icon: Mic2 },
  { id: "rocket", label: "Future", Icon: Rocket },
  { id: "zap", label: "Energy", Icon: Zap },
  { id: "flame", label: "Trend", Icon: Flame },
  { id: "activity", label: "Activity", Icon: Activity },
  { id: "anchor", label: "Anchor", Icon: Anchor },
  { id: "archive", label: "Archive", Icon: Archive },
  { id: "award", label: "Award", Icon: Award },
  { id: "backpack", label: "Backpack", Icon: Backpack },
  { id: "banknote", label: "Cash", Icon: Banknote },
  { id: "bar-chart", label: "Stats", Icon: BarChart3 },
  { id: "bath", label: "Bath", Icon: Bath },
  { id: "battery", label: "Battery", Icon: Battery },
  { id: "beaker", label: "Science", Icon: Beaker },
  { id: "bell", label: "Alert", Icon: Bell },
  { id: "bird", label: "Bird", Icon: Bird },
  { id: "book", label: "Book", Icon: Book },
  { id: "bookmark", label: "Bookmark", Icon: Bookmark },
  { id: "bot", label: "AI", Icon: Bot },
  { id: "box", label: "Package", Icon: Box },
  { id: "brush", label: "Design", Icon: Brush },
  { id: "calculator", label: "Math", Icon: Calculator },
  { id: "candy", label: "Candy", Icon: Candy },
  { id: "cat", label: "Pet", Icon: Cat },
  { id: "chef-hat", label: "Cooking", Icon: ChefHat },
  { id: "clipboard", label: "Notes", Icon: ClipboardList },
  { id: "cloud-rain", label: "Rain", Icon: CloudRain },
  { id: "cloud-sun", label: "Sunny", Icon: CloudSun },
  { id: "code", label: "Code", Icon: Code },
  { id: "coins", label: "Coins", Icon: Coins },
  { id: "contact", label: "Contact", Icon: Contact },
  { id: "cookie", label: "Cookie", Icon: Cookie },
  { id: "cpu", label: "Computer", Icon: Cpu },
  { id: "credit-card", label: "Card", Icon: CreditCard },
  { id: "croissant", label: "Bakery", Icon: Croissant },
  { id: "crown", label: "Premium", Icon: Crown },
  { id: "dog", label: "Dog", Icon: Dog },
  { id: "dollar", label: "Dollar", Icon: DollarSign },
  { id: "droplet", label: "Drink", Icon: Droplets },
  { id: "drum", label: "Music drum", Icon: Drum },
  { id: "egg", label: "Breakfast", Icon: Egg },
  { id: "eye", label: "View", Icon: Eye },
  { id: "factory", label: "Industry", Icon: Factory },
  { id: "feather", label: "Feather", Icon: Feather },
  { id: "file-text", label: "Document", Icon: FileText },
  { id: "fish", label: "Fish", Icon: Fish },
  { id: "footprints", label: "Walk", Icon: Footprints },
  { id: "gem", label: "Gem", Icon: Gem },
  { id: "glasses", label: "Glasses", Icon: Glasses },
  { id: "grape", label: "Grape", Icon: Grape },
  { id: "guitar", label: "Guitar", Icon: Guitar },
  { id: "hammer", label: "Build", Icon: Hammer },
  { id: "hand", label: "Hand", Icon: Hand },
  { id: "handshake", label: "Deal", Icon: Handshake },
  { id: "hard-hat", label: "Construction", Icon: HardHat },
  { id: "headset", label: "Headset", Icon: Headset },
  { id: "hospital", label: "Hospital", Icon: Hospital },
  { id: "hourglass", label: "Time", Icon: Hourglass },
  { id: "ice-cream", label: "Ice cream", Icon: IceCream },
  { id: "image", label: "Image", Icon: Image },
  { id: "inbox", label: "Inbox", Icon: Inbox },
  { id: "joystick", label: "Joystick", Icon: Joystick },
  { id: "lamp", label: "Lamp", Icon: Lamp },
  { id: "layers", label: "Layers", Icon: Layers },
  { id: "library", label: "Library", Icon: Library },
  { id: "life-buoy", label: "Support", Icon: LifeBuoy },
  { id: "link", label: "Link", Icon: Link },
  { id: "list", label: "List", Icon: List },
  { id: "lock", label: "Lock", Icon: Lock },
  { id: "luggage", label: "Luggage", Icon: Luggage },
];
