import {
  Activity,
  AlarmClock,
  Anchor,
  Apple,
  Archive,
  Award,
  Backpack,
  Baby,
  Banknote,
  BarChart3,
  Bath,
  Battery,
  Beaker,
  Bell,
  Bike,
  Bird,
  Book,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Building2,
  Bus,
  Calculator,
  Calendar,
  Camera,
  Candy,
  Car,
  Cat,
  ChefHat,
  Cherry,
  ClipboardList,
  Clock3,
  Cloud,
  CloudRain,
  CloudSun,
  Code,
  Coffee,
  Coins,
  Compass,
  Contact,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  Dog,
  DollarSign,
  Droplets,
  Drum,
  Dumbbell,
  Egg,
  Eye,
  Factory,
  Feather,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Grape,
  Guitar,
  Hammer,
  Hand,
  HandHeart,
  Handshake,
  HardHat,
  Headphones,
  Headset,
  Heart,
  Home,
  Hospital,
  Hotel,
  Hourglass,
  IceCream,
  Image,
  Inbox,
  Joystick,
  Key,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  List,
  Lock,
  Luggage,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic2,
  Microscope,
  Milk,
  Monitor,
  Moon,
  Mountain,
  Music,
  Music2,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  Package,
  Paintbrush,
  Palette,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  Pen,
  Pencil,
  PenLine,
  Phone,
  Piano,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Play,
  Plug,
  Podcast,
  Popcorn,
  Presentation,
  Printer,
  Puzzle,
  Radio,
  Rainbow,
  Receipt,
  Recycle,
  Rocket,
  Route,
  Ruler,
  Sailboat,
  Scale,
  School,
  Scissors,
  Scroll,
  Send,
  Server,
  Settings,
  Share2,
  Shell,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Signpost,
  Skull,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  Sprout,
  Stamp,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Sword,
  Syringe,
  Tablet,
  Tag,
  Target,
  Telescope,
  Tent,
  TestTube,
  Thermometer,
  ThumbsUp,
  Ticket,
  Timer,
  TrainFront,
  TreePine,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Umbrella,
  User,
  UserCheck,
  UserPlus,
  Users,
  UtensilsCrossed,
  Vegan,
  Video,
  Volume2,
  Wallet,
  Watch,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type SpeakingTopicIconTone = "purple" | "blue" | "green" | "orange" | "pink";

const ICON_MAP: Record<string, LucideIcon> = {
  home: Home,
  briefcase: Briefcase,
  users: Users,
  baby: Baby,
  heart: Heart,
  "hand-heart": HandHeart,
  smile: Smile,
  clock: Clock3,
  "alarm-clock": AlarmClock,
  calendar: Calendar,
  sun: Sun,
  cloud: Cloud,
  moon: Moon,
  utensils: UtensilsCrossed,
  coffee: Coffee,
  apple: Apple,
  cherry: Cherry,
  plane: Plane,
  car: Car,
  bus: Bus,
  ship: Ship,
  "map-pin": MapPin,
  compass: Compass,
  globe: Globe,
  mountain: Mountain,
  tent: Tent,
  "tree-pine": TreePine,
  waves: Waves,
  flower: Flower2,
  leaf: Leaf,
  monitor: Monitor,
  laptop: Laptop,
  smartphone: Smartphone,
  phone: Phone,
  wifi: Wifi,
  headphones: Headphones,
  gamepad: Gamepad2,
  tv: Tv,
  film: Film,
  camera: Camera,
  music: Music,
  newspaper: Newspaper,
  mail: Mail,
  megaphone: Megaphone,
  "shopping-bag": ShoppingBag,
  wallet: Wallet,
  gift: Gift,
  key: Key,
  shield: Shield,
  "book-open": BookOpen,
  school: School,
  "graduation-cap": GraduationCap,
  languages: Languages,
  "pen-line": PenLine,
  lightbulb: Lightbulb,
  brain: Brain,
  target: Target,
  star: Star,
  trophy: Trophy,
  dumbbell: Dumbbell,
  bike: Bike,
  stethoscope: Stethoscope,
  pill: Pill,
  building: Building2,
  landmark: Landmark,
  hotel: Hotel,
  flag: Flag,
  sparkles: Sparkles,
  palette: Palette,
  "message-circle": MessageCircle,
  mic: Mic2,
  rocket: Rocket,
  zap: Zap,
  flame: Flame,
  activity: Activity,
  anchor: Anchor,
  archive: Archive,
  award: Award,
  backpack: Backpack,
  banknote: Banknote,
  "bar-chart": BarChart3,
  bath: Bath,
  battery: Battery,
  beaker: Beaker,
  bell: Bell,
  bird: Bird,
  book: Book,
  bookmark: Bookmark,
  bot: Bot,
  box: Box,
  brush: Brush,
  calculator: Calculator,
  candy: Candy,
  cat: Cat,
  "chef-hat": ChefHat,
  clipboard: ClipboardList,
  "cloud-rain": CloudRain,
  "cloud-sun": CloudSun,
  code: Code,
  coins: Coins,
  contact: Contact,
  cookie: Cookie,
  cpu: Cpu,
  "credit-card": CreditCard,
  croissant: Croissant,
  crown: Crown,
  dog: Dog,
  dollar: DollarSign,
  droplet: Droplets,
  drum: Drum,
  egg: Egg,
  eye: Eye,
  factory: Factory,
  feather: Feather,
  "file-text": FileText,
  fish: Fish,
  footprints: Footprints,
  gem: Gem,
  glasses: Glasses,
  grape: Grape,
  guitar: Guitar,
  hammer: Hammer,
  hand: Hand,
  handshake: Handshake,
  "hard-hat": HardHat,
  headset: Headset,
  hospital: Hospital,
  hourglass: Hourglass,
  "ice-cream": IceCream,
  image: Image,
  inbox: Inbox,
  joystick: Joystick,
  lamp: Lamp,
  layers: Layers,
  library: Library,
  "life-buoy": LifeBuoy,
  link: Link,
  list: List,
  lock: Lock,
  luggage: Luggage,
  magnet: Magnet,
  map: MapIcon,
  medal: Medal,
  "message-square": MessageSquare,
  microscope: Microscope,
  milk: Milk,
  music2: Music2,
  navigation: Navigation,
  network: Network,
  notebook: Notebook,
  paintbrush: Paintbrush,
  parking: ParkingCircle,
  party: PartyPopper,
  paw: PawPrint,
  pen: Pen,
  pencil: Pencil,
  piano: Piano,
  "pie-chart": PieChart,
  "piggy-bank": PiggyBank,
  pizza: Pizza,
  play: Play,
  plug: Plug,
  podcast: Podcast,
  popcorn: Popcorn,
  presentation: Presentation,
  printer: Printer,
  puzzle: Puzzle,
  radio: Radio,
  rainbow: Rainbow,
  receipt: Receipt,
  recycle: Recycle,
  route: Route,
  ruler: Ruler,
  sailboat: Sailboat,
  scale: Scale,
  scissors: Scissors,
  scroll: Scroll,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share2,
  shell: Shell,
  shirt: Shirt,
  "shopping-cart": ShoppingCart,
  shovel: Shovel,
  shower: ShowerHead,
  signpost: Signpost,
  skull: Skull,
  snowflake: Snowflake,
  sofa: Sofa,
  soup: Soup,
  speaker: Speaker,
  sprout: Sprout,
  stamp: Stamp,
  store: Store,
  sunrise: Sunrise,
  sunset: Sunset,
  sword: Sword,
  syringe: Syringe,
  tablet: Tablet,
  tag: Tag,
  telescope: Telescope,
  "test-tube": TestTube,
  thermometer: Thermometer,
  "thumbs-up": ThumbsUp,
  ticket: Ticket,
  timer: Timer,
  train: TrainFront,
  "trending-up": TrendingUp,
  triangle: Triangle,
  truck: Truck,
  turtle: Turtle,
  umbrella: Umbrella,
  user: User,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  vegan: Vegan,
  video: Video,
  volume: Volume2,
  watch: Watch,
  wheat: Wheat,
  wind: Wind,
  wine: Wine,
  wrench: Wrench,
};

export function resolveSpeakingTopicIcon(iconId: string | null | undefined): LucideIcon | null {
  if (!iconId) return null;
  return ICON_MAP[iconId] ?? null;
}

export function isSpeakingTopicIconTone(value: string | null | undefined): value is SpeakingTopicIconTone {
  return value === "purple" || value === "blue" || value === "green" || value === "orange" || value === "pink";
}
